### ISSUE TITLE
Incorporate updates from v5.1 of the SRD

### ISSUE THREAD

**Issue by thomax** [eepMoody/open5e#158]
How did you move from pdf --> rst in the first place?

**Comment by maxrothman** [comment]
We were just talking about this actually, but none of us have had the time to do it yet. We originally used [pandoc](http://pandoc.org) to convert the first PDF to RST, but we then had to manually go through the results and fix errors, split things up, etc. (We think we caught all the errors, but every so often someone finds one we missed.)

Our plan on how to approach this issue was:

# Use pandoc to convert the old SRD to RST
# Use pandoc to convert the new SRD to PDF
# Diff them, apply updates to the site manually

It's a little slow, but it should get the job done and work for future updates.

**Comment by thomax** [comment]
This sounds like an excellent plan. As far as I've heard, the diff between 5.0 and 5.1 isn't too large.

**Comment by thomax** [comment]
There's this thread over at http://www.enworld.org/forum/content.php?3426-D-D-System-Reference-Document-Updated which might serve as a rough checklist as to what's new.

**Comment by maxrothman** [comment]
The full diff of changes can be found on the [SRD-5.1 branch](https://github.com/eepMoody/open5e/tree/SRD-5.1) [here](https://raw.githubusercontent.com/eepMoody/open5e/SRD-5.1/srd-source/1.1-5.1-diff.txt). As we work through the changes, we should add them to that branch and note their completion somehow. (In this issue? In that file?)

In the diff, added sections look like `{+this+}` and removed sections look like `[-this-]`.

**Comment by maxrothman** [comment]
I've been adding the line of the diff I leave off at in commit messages on that branch. If anyone else jumps in, please do the same.

**Comment by eepMoody** [comment]
I think we're up-to-date at this point. Feel free to re-open if we missed something!
