### ISSUE TITLE
Remove line breaks in source files

### ISSUE THREAD

**Issue by thomax** [eepMoody/open5e#159]
Most source files (the ones I have seen, at least) have line breaks at around col 65-90. These line breaks are carried over to the final HTML, which produces odd markup, not seen in the browser, but still.

If readability for developers is the reason for this, why not use "soft wrap" the editor of choice?

**Comment by maxrothman** [comment]
Thanks for contributing!

Though the line breaks in compiled HTML are unfortunate, bringing whole paragraphs onto one line would make tracking changes via git much more difficult, since any change in a paragraph would be shown as a change for that paragraph's line. I think the advantages of increased granularity in git history outweigh the disadvantages of slightly less pretty HTML output.

One way to address both concerns might be to write a Sphinx plugin that removed "unnecessary" newlines from HTML output. However, given that writing said plugin would be fairly low priority for us right now (and might not even be desirable, since it'd increase the code footprint of the project), I'm closing this.
