### ISSUE TITLE
Do an accessibility pass

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#34]

**Comment by eepMoody** [comment]
According to WAVE and EvalAccess our only accessibility error is that we don't have a label before the search bar. Low priority, most screenreaders can now parse the placeholder as we intend.

Other notes are that we should consider making "summaries for tables" which I'm not even sure how to do in this context (since their info can't really be summarized well) and that we should reduce how many absolute units we use (which is true, but not a blocker)
